// Generated by `wit-bindgen` 0.5.0. DO NOT EDIT!
#ifndef __BINDINGS_MD5_H
#define __BINDINGS_MD5_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct {
  uint8_t *ptr;
  size_t len;
} md5_list_u8_t;

typedef struct {
  uint64_t bytes;
  uint32_t a;
  uint32_t b;
  uint32_t c;
  uint32_t d;
  md5_list_u8_t buffer;
} md5hash_context_t;

// Exported Functions from `md5`
void md5_init(md5hash_context_t *ret);
int32_t md5_update(md5hash_context_t *ctx, md5_list_u8_t *msg);
void md5_final(md5hash_context_t *ctx, md5_list_u8_t *ret);

// Helper Functions

void md5_list_u8_free(md5_list_u8_t *ptr);
void md5hash_context_free(md5hash_context_t *ptr);

#ifdef __cplusplus
}
#endif
#endif
