// Generated by `wit-bindgen` 0.5.0. DO NOT EDIT!
#include "md5.h"

__attribute__((weak, export_name("cabi_post_md5#init")))
void __wasm_export_md5_init_post_return(int32_t arg0) {
  int32_t ptr = *((int32_t*) (arg0 + 24));
  int32_t len = *((int32_t*) (arg0 + 28));
  for (int32_t i = 0; i < len; i++) {
    int32_t base = ptr + i * 1;
    (void) base;
  }
  if (len > 0) {
    free((void*) (ptr));
  }
}
__attribute__((weak, export_name("cabi_post_md5#final")))
void __wasm_export_md5_final_post_return(int32_t arg0) {
  int32_t ptr = *((int32_t*) (arg0 + 0));
  int32_t len = *((int32_t*) (arg0 + 4));
  for (int32_t i = 0; i < len; i++) {
    int32_t base = ptr + i * 1;
    (void) base;
  }
  if (len > 0) {
    free((void*) (ptr));
  }
}

__attribute__((weak, export_name("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void md5_list_u8_free(md5_list_u8_t *ptr) {
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void md5hash_context_free(md5hash_context_t *ptr) {
  md5_list_u8_free(&ptr->buffer);
}

// Component Adapters

__attribute__((aligned(8)))
static uint8_t RET_AREA[32];

__attribute__((export_name("md5#init")))
int32_t __wasm_export_md5_init(void) {
  md5hash_context_t ret;
  md5_init(&ret);
  int32_t ptr = (int32_t) &RET_AREA;
  *((int64_t*)(ptr + 0)) = (int64_t) ((ret).bytes);
  *((int32_t*)(ptr + 8)) = (int32_t) ((ret).a);
  *((int32_t*)(ptr + 12)) = (int32_t) ((ret).b);
  *((int32_t*)(ptr + 16)) = (int32_t) ((ret).c);
  *((int32_t*)(ptr + 20)) = (int32_t) ((ret).d);
  *((int32_t*)(ptr + 28)) = (int32_t) ((ret).buffer).len;
  *((int32_t*)(ptr + 24)) = (int32_t) ((ret).buffer).ptr;
  return ptr;
}

__attribute__((export_name("md5#update")))
int32_t __wasm_export_md5_update(int64_t arg, int32_t arg0, int32_t arg1, int32_t arg2, int32_t arg3, int32_t arg4, int32_t arg5, int32_t arg6, int32_t arg7) {
  md5hash_context_t arg8 = (md5hash_context_t) {
    (uint64_t) (arg),
    (uint32_t) (arg0),
    (uint32_t) (arg1),
    (uint32_t) (arg2),
    (uint32_t) (arg3),
    (md5_list_u8_t) { (uint8_t*)(arg4), (size_t)(arg5) },
  };
  md5_list_u8_t arg9 = (md5_list_u8_t) { (uint8_t*)(arg6), (size_t)(arg7) };
  int32_t ret = md5_update(&arg8, &arg9);
  return ret;
}

__attribute__((export_name("md5#final")))
int32_t __wasm_export_md5_final(int64_t arg, int32_t arg0, int32_t arg1, int32_t arg2, int32_t arg3, int32_t arg4, int32_t arg5) {
  md5hash_context_t arg6 = (md5hash_context_t) {
    (uint64_t) (arg),
    (uint32_t) (arg0),
    (uint32_t) (arg1),
    (uint32_t) (arg2),
    (uint32_t) (arg3),
    (md5_list_u8_t) { (uint8_t*)(arg4), (size_t)(arg5) },
  };
  md5_list_u8_t ret;
  md5_final(&arg6, &ret);
  int32_t ptr = (int32_t) &RET_AREA;
  *((int32_t*)(ptr + 4)) = (int32_t) (ret).len;
  *((int32_t*)(ptr + 0)) = (int32_t) (ret).ptr;
  return ptr;
}

extern void __component_type_object_force_link_md5(void);
void __component_type_object_force_link_md5_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_md5();
}
