interface md5hash {
  record context {
    bytes: u64,
    a: u32,
    b: u32,
    c: u32,
    d: u32,
    buffer: list<u8>,
  }

  enum errno {
    error,
  }
  
  init: func() -> result<context, errno>
  update: func(ctx: context, msg: list<u8>) -> result<context, errno>
  hash: func(ctx: context) -> result<list<u8>, errno>
}

default world md5 {
  export md5: self.md5hash
}
